export const STAGE_WIDTH = 700;
export const STAGE_HEIGHT = 450;
export const BAR_WIDTH = 384;
//export const NOTES_GRID_WIDTH = 1920;
export const NOTES_GRID_WIDTH = BAR_WIDTH * 4;
export const NOTES_GRID_HEIGHT = 2160;
export const ROW_HEIGHT = 20;
export const PIANO_KEY_WIDTH = 120;
export const SCROLLBAR_WIDTH = 24;
export const SCROLLBAR_THUMB_LENGTH = 40;
export const SCROLLBAR_GUTTER = 4;


export const DRAG_MODE_ADJUST_NEW_NOTE_SIZE = 'DRAG_MODE_ADJUST_NEW_NOTE_SIZE';
export const DRAG_MODE_ADJUST_EXISTING_NOTE_SIZE = 'DRAG_MODE_ADJUST_EXISTING_NOTE_SIZE';
export const DRAG_MODE_ADJUST_SELECTED_NOTES_SIZE = 'DRAG_MODE_ADJUST_SELECTED_NOTES_SIZE';
export const DRAG_MODE_ADJUST_SELECTED_NOTES_POSITION = 'DRAG_MODE_ADJUST_SELECTED_NOTES_POSITION';
export const DRAG_MODE_SELECT_NOTES = 'DRAG_MODE_SELECT_NOTES';

export const DRAG_MODE_ADJUST_NOTE_POSITION = 'DRAG_MODE_ADJUST_NOTE_POSITION';
export const DRAG_MODE_ADJUST_NOTE_SIZE = 'DRAG_MODE_ADJUST_NOTE_SIZE';
export const DRAG_MODE_ADJUST_SELECTION = 'DRAG_MODE_ADJUST_SELECTION';

export const ACTIVE_TOOL_CURSOR = 'ACTIVE_TOOL_CURSOR';
export const ACTIVE_TOOL_PENCIL = 'ACTIVE_TOOL_PENCIL';
export const ACTIVE_TOOL_MARQUEE = 'ACTIVE_TOOL_MARQUEE';
