export const QUANTIZE_VALUE_UPDATE = 'QUANTIZE_VALUE_UPDATE';
export const NOTE_DURATION_UPDATE = 'NOTE_DURATION_UPDATE';
export const ADD_NOTE = 'ADD_NOTE';
export const ACTIVE_TOOL_UPDATE = 'ACTIVE_TOOL_UPDATE';